---
name: bosh-skynet
director_uuid: 8e592648-9c4a-4d9d-9b43-c86e5fd843f6

release:                                            
  name: bosh-tempest 
  version: latest 

networks:
- name: default # An internal name for the network in your manifest file
  subnets:
  - reserved:
    - 10.0.0.2 - 10.0.0.100
    static:
    - 10.0.0.101 - 10.0.0.130
    range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns:
    - 10.0.0.1
    cloud_properties:
      name: "tempest-org-vdc-nw"      

#
# You shouldn't have to change any of the resource pool parameters
#

resource_pools:
- name: small
  stemcell:
    name: bosh-stemcell
    version: 0.8.0
  network: default
  size: 5
  cloud_properties:
    ram: 512
    disk: 2048
    cpu: 1
  env:
    bosh:
      password: "$6$66pTgip9$1FgWAj2uKEUUQj1cnJKXm9xdnhd.jJKmERB/o4Mc/8PPOp8ba6FTv206M3RzPOuZdPlifNjLJaGzysz0OfXxV0"

- name: director
  stemcell:
    name: bosh-stemcell
    version: 0.8.0
  network: default
  size: 1
  cloud_properties:
    ram:  2048
    disk: 8192
    cpu: 2
  env:
    bosh:
      password: "$6$66pTgip9$1FgWAj2uKEUUQj1cnJKXm9xdnhd.jJKmERB/o4Mc/8PPOp8ba6FTv206M3RzPOuZdPlifNjLJaGzysz0OfXxV0"

compilation:
  workers: 2
  network: default
  cloud_properties:
    ram: 2048
    disk: 4048
    cpu: 2

#
# If you have errors with canary instances during a deployment, you can try 
# increasing the canary_watch_time and update_watch_time. The values here are in 
# milliseconds. Divide by 1000 to get the value in seconds.
# 
#

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 1
  max_errors: 2

jobs:

- name: nats
  template: nats
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.0.0.120

- name: postgres
  template: postgres
  instances: 1
  resource_pool: small
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.0.0.121

- name: redis
  template: redis
  instances: 1 
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.0.0.122

- name: director
  template: director
  instances: 1
  resource_pool: director
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.0.0.123

- name: blobstore
  template: blobstore
  instances: 1
  resource_pool: small
  persistent_disk: 8192
  networks:
  - name: default
    static_ips:
    - 10.0.0.124

- name: health_monitor
  template: health_monitor
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.0.0.125

properties:
  env:

  blobstore:
    address: 10.0.0.124
    port: 25251
    backend_port: 25552
    agent:
      user: agent
      password: 38fh20
    director:
      user: director
      password: oe9U37dbd

  networks:
    apps: default
    management: default

  nats:
    user: nats              
    password: 38dhj389ddck378gcE
    address: 10.0.0.120
    port: 4222

  postgres:
    user: bosh             
    password: 29fhcuebJDldhv265kB
    address: 10.0.0.121
    port: 5432
    database: bosh

  redis:
    address: 10.0.0.122
    port: 25255
    password: wicjew93hf2

  director:
    name: skynet-bosh
    address: 10.0.0.123
    port: 25555

  hm:
    http:
      port: 25923
      user: admin
      password: admin
    director_account:
      user: admin
      password: admin
    intervals:
      poll_director: 60
      poll_grace_period: 30
      log_stats: 300
      analyze_agents: 60
      agent_timeout: 180
      rogue_agent_alert: 180
    loglevel: info
    email_notifications: false
    email_recipients:
    - noemail@yourdomain.com
    smtp:
      from: bhm@localhost.localdomain
      host: smtp.vmware.com
      port: 25
      auth: plain
      user: appcloud
      password: 38fhsoeY
      domain: localdomain
    tsdb_enabled: false     # If this option is set to false, comment out its params.
    #tsdb:
    #  address: 10.1.4.228
    #  port: 4242

  vcd:
    url: https://10.0.0.6
    user: admin
    password: password
    entities:
      organization: tempest
      virtual_datacenter: tempest-org-vdc
      vapp_catalog: cloudfoundry
      media_catalog: cloudfoundry
      media_storage_profile: *
      vm_metadata_key: cf-agent-env
