---
name: bosh-skynet
director_uuid: dc08697a-c6b8-4ad4-b3a6-bd250779db11

release:                                            
  name: bosh-tempest
  version: latest 

networks:
- name: default # An internal name for the network in your manifest file
  subnets:
  - reserved:
    - 192.168.109.2 - 192.168.109.29
    static:
    - 192.168.109.30 - 192.168.109.50
    range: 192.168.109.0/24
    gateway: 192.168.109.1
    dns:
    - 192.168.109.1
    cloud_properties:
      name: "VDC-26852-120815-121-default-routed"

#
# You shouldn't have to change any of the resource pool parameters
#

resource_pools:
- name: small
  stemcell:
    name: bosh-stemcell
    version: 750
  network: default
  size: 5
  cloud_properties:
    ram: 512
    disk: 2048
    cpu: 1
  env:
#    bosh:
#      password: "$6$66pTgip9$1FgWAj2uKEUUQj1cnJKXm9xdnhd.jJKmERB/o4Mc/8PPOp8ba6FTv206M3RzPOuZdPlifNjLJaGzysz0OfXxV0"
    vapp: bosh_small

- name: director
  stemcell:
    name: bosh-stemcell
    version: 750
  network: default
  size: 1
  cloud_properties:
    ram:  2048
    disk: 8192
    cpu: 2
  env:
#    bosh:
#      password: "$6$66pTgip9$1FgWAj2uKEUUQj1cnJKXm9xdnhd.jJKmERB/o4Mc/8PPOp8ba6FTv206M3RzPOuZdPlifNjLJaGzysz0OfXxV0"
    vapp: bosh_director

compilation:
  workers: 4
  network: default
  cloud_properties:
    ram: 2048
    disk: 4048
    cpu: 2

#
# If you have errors with canary instances during a deployment, you can try 
# increasing the canary_watch_time and update_watch_time. The values here are in 
# milliseconds. Divide by 1000 to get the value in seconds.
# 
#

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 1
  max_errors: 2

jobs:

- name: nats
  template: nats
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 192.168.109.30

- name: postgres
  template: postgres
  instances: 1
  resource_pool: small
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.168.109.31

- name: redis
  template: redis
  instances: 1 
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 192.168.109.32

- name: director
  template: director
  instances: 1
  resource_pool: director
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 192.168.109.33

- name: blobstore
  template: blobstore
  instances: 1
  resource_pool: small
  persistent_disk: 16384
  networks:
  - name: default
    static_ips:
    - 192.168.109.34

- name: health_monitor
  template: health_monitor
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 192.168.109.35

properties:
  env:

  blobstore:
    address: 192.168.109.34
    port: 25251
    backend_port: 25552
    agent:
      user: agent
      password: 38fh20
    director:
      user: director
      password: oe9U37dbd

  networks:
    apps: default
    management: default

  nats:
    user: nats              
    password: 38dhj389ddck378gcE
    address: 192.168.109.30
    port: 4222

  postgres:
    user: bosh             
    password: 29fhcuebJDldhv265kB
    address: 192.168.109.31
    port: 5432
    database: bosh

  redis:
    address: 192.168.109.32
    port: 25255
    password: wicjew93hf2

  director:
    name: skynet-bosh
    address: 192.168.109.33
    port: 25555
    db:
      user: director
      password: password

  hm:
    http:
      port: 25923
      user: admin
      password: admin
    director_account:
      user: admin
      password: admin
    intervals:
      poll_director: 60
      poll_grace_period: 30
      log_stats: 300
      analyze_agents: 60
      agent_timeout: 180
      rogue_agent_alert: 180
    loglevel: info
    email_notifications: false
    email_recipients:
    - noemail@yourdomain.com
    smtp:
      from: bhm@localhost.localdomain
      host: smtp.vmware.com
      port: 25
      auth: plain
      user: appcloud
      password: 38fhsoeY
      domain: localdomain
    tsdb_enabled: false     # If this option is set to false, comment out its params.

  vcd:
    url: https://p3v5-vcd.vchs-int.vmware.com
    user: hgadgil@vmware.com
    password: Pa$$w0rd
    entities:
      organization: VDC-26852-120815-121
      virtual_datacenter: VDC-26852-120815-121
      vapp_catalog: bosh 
      media_catalog: bosh
      media_storage_profile: "*"
      vm_metadata_key: cf-agent-env
      description: Bosh on vCloudDirector
